### ISSUE TITLE
Can't import package

### ISSUE THREAD

**Issue by kix2mix2** [maljovec/pyerg#13]
Hi, I've been trying for a couple days to install this package, I had lots of issues installing it (due to some gcc error people seem to be having with other packages) in the first place but finally I managed. In either case now I cannot actually import the package because I get the following error. 

```
import nglpy
Traceback (most recent call last):
  File "/anaconda3/envs/SepMe/lib/python3.7/site-packages/nglpy/ngl.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_ngl', [dirname(__file__)])
  File "/anaconda3/envs/SepMe/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_ngl'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/anaconda3/envs/SepMe/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-eae6d9e3d0bd>", line 1, in <module>
    import nglpy
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/envs/SepMe/lib/python3.7/site-packages/nglpy/__init__.py", line 37, in <module>
    from .Graph import Graph
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/envs/SepMe/lib/python3.7/site-packages/nglpy/Graph.py", line 43, in <module>
    from .ngl import nglGraph, vectorInt, vectorDouble
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/envs/SepMe/lib/python3.7/site-packages/nglpy/ngl.py", line 28, in <module>
    _ngl = swig_import_helper()
  File "/anaconda3/envs/SepMe/lib/python3.7/site-packages/nglpy/ngl.py", line 20, in swig_import_helper
    import _ngl
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/anaconda3/envs/SepMe/lib/python3.7/site-packages/_ngl.cpython-37m-darwin.so, 2): Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
  Referenced from: /anaconda3/envs/SepMe/lib/python3.7/site-packages/_ngl.cpython-37m-darwin.so
  Expected in: flat namespace
 in /anaconda3/envs/SepMe/lib/python3.7/site-packages/_ngl.cpython-37m-darwin.so
```

I'm a macOS 10.14.5 user, I install this package in a condaenv running python 3.7 using the following line: 
`env CC=/usr/local/bin/gcc-4.9 pip install nglpy`

**Comment by dmaljovec** [comment]
Hmm, sorry about the issues with installing. This is the line that jumped out at me:

```
ImportError: dlopen(/anaconda3/envs/SepMe/lib/python3.7/site-packages/_ngl.cpython-37m-darwin.so, 2): Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
```

I poked around real quickly for where this comes from and there seem to be others with this issue in different places:
 * [(clang++) Symbol not found from libstdc++.6.0.9.dylib](https://stackoverflow.com/questions/47953595/clang-symbol-not-found-from-libstdc-6-0-9-dylib)
 * [help-libtorrent-python-bindings-macosx.md](https://gist.github.com/gubatron/e6c10f984965b6bd412a)

Though I don't see the immediate solution on those cases, it does appear to be some sort of compiler incompatibility. This could point to the problems you were having upstream in getting the project to build/install in the first place. Can you explain what the problems were there? It would be great if there is something I can fix in the setup.py to make this more user-friendly.

For example, I would be curious to why you needed to specify the specific C compiler.

I have a macOS 10.14.6 machine that I can test this out on now to see if I can replicate the issue.

**Comment by dmaljovec** [comment]
Test setup on macOS 10.14.6 (I am omitting some of the output for brevity):

```
$ conda create -n ngl_test python=3.7
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.7.11

[output truncated]

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate ngl_test
#
# To deactivate an active environment, use
#
#     $ conda deactivate
$ conda activate ngl_test
(ngl_test) $ pip install nglpy
Collecting nglpy
  Downloading https://files.pythonhosted.org/packages/1a/4c/5556f455b88aa904d958f5227bbf1fb6b65e42a3d54a66656d8f02c9bebc/nglpy-0.0.2.tar.gz (77kB)
Collecting scipy (from nglpy)
  Downloading https://files.pythonhosted.org/packages/d5/06/1a696649f4b2e706c509cb9333fdc6331fbe71251cede945f9e1fa13ea34/scipy-1.3.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (27.7MB)
Collecting numpy (from nglpy)
  Downloading https://files.pythonhosted.org/packages/c1/4b/78119133136c20e5ad2e01bf72b0633241defd619939908223cd394a9c32/numpy-1.17.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (15.0MB)
Collecting scikit-learn (from nglpy)
  Downloading https://files.pythonhosted.org/packages/e9/57/8a9889d49d0d77905af5a7524fb2b468d2ef5fc723684f51f5ca63efed0d/scikit_learn-0.21.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (10.5MB)
Collecting joblib>=0.11 (from scikit-learn->nglpy)
  Using cached https://files.pythonhosted.org/packages/cd/c1/50a758e8247561e58cb87305b1e90b171b8c767b15b12a1734001f41d356/joblib-0.13.2-py2.py3-none-any.whl
Building wheels for collected packages: nglpy
  Building wheel for nglpy (setup.py) ... done

Successfully built nglpy
Installing collected packages: numpy, scipy, joblib, scikit-learn, nglpy
Successfully installed joblib-0.13.2 nglpy-0.0.2 numpy-1.17.0 scikit-learn-0.21.3 scipy-1.3.1
```

It looks like it installed okay. Let me test it real fast to make sure I don't get the weird missing symbol:

```python
>>> import nglpy
>>> import numpy as np
>>>
>>> point_set = np.random.rand(100,2)
>>> max_neighbors = 9
>>> beta = 1
>>> graph_type = 'beta skeleton'
>>> aGraph = nglpy.Graph(point_set, graph_type, max_neighbors, beta)
>>>
>>> aGraph.neighbors()
{0: (13, 29, 85, 87), 1: (18, 34, 58, 70), 2: (4, 13, 31, 54, 56, 87), 3: (4, 52, 54), 4: (2, 3, 54, 79), 5: (22, 41, 88), 6: (15, 20, 57), 7: (14, 46, 55, 60, 63), 8: (15, 75, 82, 96), 9: (17, 28, 86), 10: (61, 76, 84), 11: (50, 80), 12: (19, 22, 77, 88), 13: (0, 2, 29), 14: (7, 46, 82), 15: (6, 8, 53, 82), 16: (52, 59, 73, 95), 17: (9, 90), 18: (1, 67, 98), 19: (12, 38, 65, 88), 20: (6, 40, 53, 57, 60), 21: (64, 80), 22: (5, 12, 77, 88), 23: (37, 96), 24: (47, 50, 70, 80, 83), 25: (50, 93), 26: (68, 77, 98), 27: (32, 74, 93), 28: (9, 49, 85), 29: (0, 13, 90), 30: (31, 35, 51, 92), 31: (2, 30, 56, 87, 92), 32: (27, 69, 72, 74), 33: (43, 54, 56, 73), 34: (1, 45), 35: (30, 81, 92), 36: (44, 51), 37: (23,), 38: (19, 59, 97), 39: (41, 61, 71, 84), 40: (20, 49, 57, 85), 41: (5, 39), 42: (43, 59, 73), 43: (33, 42), 44: (36, 68), 45: (34, 55, 78), 46: (7, 14, 55, 64), 47: (24, 78), 48: (62, 95, 99), 49: (28, 40, 57, 86), 50: (11, 24, 25), 51: (30, 36, 87), 52: (3, 16, 73), 53: (15, 20, 60, 82), 54: (2, 3, 4, 33, 56), 55: (7, 45, 46, 63), 56: (2, 31, 33, 54, 92), 57: (6, 20, 40, 49), 58: (1, 70), 59: (16, 38, 42, 95, 99), 60: (7, 20, 53), 61: (10, 39, 71), 62: (48, 89), 63: (7, 55, 67), 64: (21, 46), 65: (19, 81), 66: (79,), 67: (18, 63, 98), 68: (26, 44, 77), 69: (32, 71, 72), 70: (1, 24, 58, 78, 83), 71: (39, 61, 69), 72: (32, 69, 83), 73: (16, 33, 42, 52), 74: (27, 32, 93), 75: (8, 82), 76: (10, 89, 94), 77: (12, 22, 26, 68), 78: (45, 47, 70), 79: (4, 66, 91), 80: (11, 21, 24), 81: (35, 65, 92), 82: (8, 14, 15, 53, 75), 83: (24, 70, 72), 84: (10, 39, 94), 85: (0, 28, 40), 86: (9, 49), 87: (0, 2, 31, 51), 88: (5, 12, 19, 22, 97), 89: (62, 76), 90: (17, 29, 91), 91: (79, 90), 92: (30, 31, 35, 56, 81), 93: (25, 27, 74), 94: (76, 84, 99), 95: (16, 48, 59), 96: (8, 23), 97: (38, 88, 99), 98: (18, 26, 67), 99: (48, 59, 94, 97)}
>>>
```

So, I am unable to replicate your error on a similar machine which means I will need some help figuring out what is different/unique about your setup that could be causing issues.

It does look like you were running it in PyCharm. Just to disambiguate the problem, you also get the same thing when executed directly from the terminal or within a python REPL? I don't suspect the debugger to be the issue, but if it is, our life will be a lot more complicated.

I am happy to help you work through this issue.

**Comment by dmaljovec** [comment]
So, at one point I started implementing a [pure python branch](https://github.com/maljovec/nglpy/tree/pure_python), but I don't think it is ready for primetime. IIRC, it was a bit of a proving ground for the algorithm used in my GPU-enabled version of this library, [nglpy-cuda](https://github.com/maljovec/nglpy_cuda), and that branch adds an additional dependency on `numba`. I don't have hard numbers, but I believe this version was slower than the master branch's C version of the code.

If the compilation issue turns out to be an insurmountable problem, we can probably get you to a point where you can use `python setup.py install` from the pure_python branch to get unstuck. I would have to probably clean up that branch a bit first.

To be clear, ideally I would want to get your compilation problem figured out first, and use this plan as a backup, since the more performant version should be usable by everyone, not just those with a very vanilla setup like my own.

**Comment by kix2mix2** [comment]
Hey sorry, I thought I'd get an email when you reply and I didn't hence the delayed answer. In the last weeks I updated to macOS Catalina, which broke a bunch of things in my computer and forced me reinstall my anaconda distribution and other python stuff, and now this just works. I do thing you were right about the wrong compiler, I had some similar issues with other cythonic packages.

**Comment by dmaljovec** [comment]
Sorry, about your setup, but glad things are working now!
