### ISSUE TITLE
Swig issues

### ISSUE THREAD

**Issue by orpheus92** [maljovec/pyerg#2]
graph_rep.FullGraph()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/orpheus92/OS/conda/envs/Di/lib/python3.6/site-packages/pyerg/ngl.py", line 161, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, nglGraph, name)
  File "/media/orpheus92/OS/conda/envs/Di/lib/python3.6/site-packages/pyerg/ngl.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/media/orpheus92/OS/conda/envs/Di/lib/python3.6/site-packages/pyerg/ngl.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'

>>> graph_rep.Neighbors()
swig/python detected a memory leak of type 'std::map< int,std::set< int,std::less< int >,std::allocator< int > >,std::less< int >,std::allocator< std::pair< int const,std::set< int,std::less< int >,std::allocator< int > > > > > *', no destructor found.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/orpheus92/OS/conda/envs/Di/lib/python3.6/site-packages/pyerg/Graph.py", line 93, in Neighbors
    return dict(super(Graph, self).Neighbors())
TypeError: 'SwigPyObject' object is not iterable
>>>

**Comment by maljovec** [comment]
Closing since I believe we fixed this issue by updating the version number and reinstalling.
